# Generated by Django 5.2.9 on 2026-03-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelog',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
