# Generated by Django 5.0.8 on 2024-08-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MarketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('api_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10)),
                ('application_time', models.FloatField()),
                ('database_time', models.FloatField()),
                ('endpoint_url', models.URLField()),
                ('request_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TradeCpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('replica_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application_time', models.FloatField()),
                ('database_time', models.FloatField()),
                ('number_of_sell_offers', models.IntegerField()),
                ('number_of_buy_offers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrafficCpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.CharField(max_length=255)),
                ('api_time', models.FloatField()),
            ],
        ),
    ]
