# Generated by Django 5.2.13 on 2026-04-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0002_tradelog_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradelog',
            name='user_id',
        ),
    ]
