# Generated by Django 5.1 on 2024-08-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0002_marketcpu_marketlog_tradecpu_tradelog_trafficcpu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('contener_id', models.CharField()),
            ],
        ),
        migrations.DeleteModel(
            name='MarketCpu',
        ),
        migrations.DeleteModel(
            name='TradeCpu',
        ),
        migrations.DeleteModel(
            name='TrafficCpu',
        ),
    ]
