# Generated by Django 5.1 on 2024-09-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0003_cpu_delete_marketcpu_delete_tradecpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelog',
            name='company_ids',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
