# Generated by Django 5.1.1 on 2024-09-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0004_tradelog_company_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balanceupdate',
            old_name='change_amount',
            new_name='changeAmount',
        ),
        migrations.RenameField(
            model_name='balanceupdate',
            old_name='change_type',
            new_name='changeType',
        ),
        migrations.RenameField(
            model_name='balanceupdate',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='contener_id',
            new_name='contenerId',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='cpu_usage',
            new_name='cpuUsage',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='memory_usage',
            new_name='memoryUsage',
        ),
        migrations.RenameField(
            model_name='marketlog',
            old_name='api_method',
            new_name='apiMethod',
        ),
        migrations.RenameField(
            model_name='marketlog',
            old_name='application_time',
            new_name='applicationTime',
        ),
        migrations.RenameField(
            model_name='marketlog',
            old_name='database_time',
            new_name='databaseTime',
        ),
        migrations.RenameField(
            model_name='marketlog',
            old_name='endpoint_url',
            new_name='endpointUrl',
        ),
        migrations.RenameField(
            model_name='marketlog',
            old_name='request_id',
            new_name='requestId',
        ),
        migrations.RenameField(
            model_name='stockrate',
            old_name='date_inc',
            new_name='dateInc',
        ),
        migrations.RenameField(
            model_name='tradelog',
            old_name='application_time',
            new_name='applicationTime',
        ),
        migrations.RenameField(
            model_name='tradelog',
            old_name='company_ids',
            new_name='companyIds',
        ),
        migrations.RenameField(
            model_name='tradelog',
            old_name='database_time',
            new_name='databaseTime',
        ),
        migrations.RenameField(
            model_name='tradelog',
            old_name='number_of_buy_offers',
            new_name='numberOfBuyOffers',
        ),
        migrations.RenameField(
            model_name='tradelog',
            old_name='number_of_sell_offers',
            new_name='numberOfSellOffers',
        ),
        migrations.RenameField(
            model_name='trafficlog',
            old_name='api_time',
            new_name='apiTime',
        ),
        migrations.RenameField(
            model_name='trafficlog',
            old_name='request_id',
            new_name='requestid',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='total_price',
            new_name='totalPrice',
        ),
    ]
