# Generated by Django 5.2.4 on 2025-07-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0006_trafficlog_userclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketlog',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
